apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtd-fe-admin-v2
  labels:
    app: vtd-fe-admin-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtd-fe-admin-v2
  template:
    metadata:
      labels:
        app: vtd-fe-admin-v2
    spec:
      containers:
        - name: vtd-fe-admin-v2
          image: asia-southeast1-docker.pkg.dev/spartan-impact-319504/vtd-dev/vtd-fe-admin-v2:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BASE_URL
              value: 'https://api-stg.vitadairyvietnam.vn/api'
